const menuTypes = {
  SET_OPEN_DATA_MODAL: "SET_OPEN_DATA_MODAL",
  SET_OPEN_SETTINGS_MODAL: "SET_OPEN_SETTINGS_MODAL",
  SET_OPEN_LEFT_SIDEBAR: "SET_OPEN_LEFT_SIDEBAR",
  SET_OPEN_RIGHT_SIDEBAR: "SET_OPEN_RIGHT_SIDEBAR",
  SET_CONCEPTS: "SET_CONCEPTS",
  SET_RELEATIONS: "SET_RELEATIONS",
};

export default menuTypes;
